"""Lane C — generate a punchy, YouTube-ready title for a rendered short.

Each detected moment gets ONE real title (no templated filler): a scroll-stopping
headline generated by GPT from the moment's REAL hook + verbatim quote + topic. The SAME
title is used two ways so the viewer and the platform see the same thing:

  1. burned across the top of the vertical clip so the audience sees it
     (``engine/overlay.py``), and
  2. the YouTube video title at upload (dashboard ``/api/youtube/upload``).

When ``OPENAI_API_KEY`` is missing (or the call fails) we fall back to a clean derivation
of the real hook/quote so a title always exists — never blank, never invented metrics.
The optional ``hook_style`` lets Lane B's self-learning loop steer the title voice, the
same way it already steers moment/hook detection.
"""
from __future__ import annotations

import json
import os
import re

from shared.redis_client import coord

# YouTube hard-caps titles at 100 chars; we aim shorter so it also reads well burned on the
# clip (a wall of text up top looks bad). This is the on-screen + metadata target length.
MAX_TITLE_CHARS = 100
TARGET_TITLE_CHARS = 70


def _clean(title: str) -> str:
    """Normalize an LLM/derived title: strip wrapping quotes, collapse whitespace, cap."""
    if not title:
        return ""
    title = re.sub(r"\s+", " ", title).strip()
    # Drop a trailing hashtag tail if the model added one despite instructions, THEN strip
    # any quotes wrapping the whole title (order matters so `"…" #tag` cleans fully).
    title = re.sub(r"\s+#\S.*$", "", title).strip()
    title = title.strip("\"'“”‘’").strip()
    if len(title) > MAX_TITLE_CHARS:
        title = title[: MAX_TITLE_CHARS - 1].rstrip() + "…"
    return title


def _fallback_title(hook: str, quote: str, topic: str, source_title: str) -> str:
    """Best real title we can build with no LLM: prefer the hook, then quote, then topic."""
    for candidate in (hook, quote, source_title, topic):
        c = _clean(candidate or "")
        if len(c) >= 8:
            if len(c) > TARGET_TITLE_CHARS:
                c = c[: TARGET_TITLE_CHARS - 1].rstrip() + "…"
            return c
    return _clean(source_title) or "Podcast moment"


def generate_title(
    *,
    hook: str = "",
    quote: str = "",
    topic: str = "",
    source_title: str = "",
    hook_style: str = "",
) -> str:
    """Return one punchy, faithful, <=100-char title for a clip.

    Uses GPT when ``OPENAI_API_KEY`` is set, otherwise a clean derivation of the real hook.
    Never raises — any failure degrades to the deterministic fallback.
    """
    fallback = _fallback_title(hook, quote, topic, source_title)
    if not os.getenv("OPENAI_API_KEY"):
        return fallback

    style_line = (
        f"\nMatch this proven winning voice: {hook_style}." if hook_style else ""
    )
    prompt = (
        "You write titles for viral short-form podcast clips. Write ONE title for this "
        "clip that maximizes click-through without lying about the content.\n"
        f"- Faithful to the actual moment (do not invent claims).\n"
        f"- {TARGET_TITLE_CHARS} characters or fewer, {MAX_TITLE_CHARS} hard max.\n"
        "- Scroll-stopping and specific; curiosity or a bold real claim.\n"
        "- No surrounding quotes, no hashtags, no emojis, no clickbait that misleads."
        f"{style_line}\n\n"
        f"TOPIC: {topic or 'n/a'}\n"
        f"HOOK: {hook or 'n/a'}\n"
        f"VERBATIM QUOTE: {quote or 'n/a'}\n"
        f"SOURCE EPISODE: {source_title or 'n/a'}\n\n"
        'Return JSON {"title": string}.'
    )
    try:
        from openai import OpenAI

        client = OpenAI()
        resp = client.chat.completions.create(
            model=os.getenv("OPENAI_MODEL", "gpt-5.5"),
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},  # gpt-5.x: default temperature only
        )
        raw = json.loads(resp.choices[0].message.content or "{}").get("title", "")
        title = _clean(raw)
        return title or fallback
    except Exception as e:  # real failure -> honest fallback, never blank
        coord("C", "error", f"title generation failed: {e}")
        return fallback
